### ISSUE TITLE
I tried to run it but its not working 

### ISSUE THREAD

**Issue by ziksat** [theIYD/coursehunt#6]
Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by theIYD** [comment]
Tell me the situation. How did this error occur? What did you do etc etc ....

**Comment by ziksat** [comment]
i run yarn  install  after that i used npm start and the error occur as i show u  fallowed ur instraction exac

**Comment by ziksat** [comment]
its working on Windows  i used .exe file but not on Mac

**Comment by theIYD** [comment]
Can you run `npm install` instead of `yarn install` ? Report back with screenshot of errors.

**Comment by theIYD** [comment]
@ziksat I will be making the application cross-platform. Before that, if anything is going wrong on building for macOS, report back with errors produced.

**Comment by theIYD** [comment]
**Update**

The application works on macOS High Sierra. Make sure you upgrade to the latest version of node.
